env_config:
  env_name: 'HalfCheetah-v2'
  max_episode_step: 1000
  env_seed: 10
  delay_reward: True

model_config:
  policy_hidden_layers:
    - 256
    - 256
  logstd_min: -5
  logstd_max: 2
  value_hidden_layers:
    - 256
    - 256
  
num_workers: 4
seed: 10
lr: 0.0003
gamma: 0.999
rho: 0.001
buffer_size: 1000000
batch_size: 256
device: 'cpu'
results_path: '/home/xukang/GitRepo/RL/IRCR/results/'
max_timestep: 800000
start_training_step: 2000
train_policy_delay: 1
save_interval: 100
soft_update_interval: 1

evaluation_interval: 1000
evaluation_rollouts: 10